# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import pbft_pb2 as pbft__pb2


class PbftServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPreprepare = channel.unary_unary(
        '/PbftService/GetPreprepare',
        request_serializer=pbft__pb2.PbftPreprepare.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetPrepare = channel.unary_unary(
        '/PbftService/GetPrepare',
        request_serializer=pbft__pb2.PbftPrepare.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetCommit = channel.unary_unary(
        '/PbftService/GetCommit',
        request_serializer=pbft__pb2.PbftCommit.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class PbftServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPreprepare(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPrepare(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCommit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PbftServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPreprepare': grpc.unary_unary_rpc_method_handler(
          servicer.GetPreprepare,
          request_deserializer=pbft__pb2.PbftPreprepare.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetPrepare': grpc.unary_unary_rpc_method_handler(
          servicer.GetPrepare,
          request_deserializer=pbft__pb2.PbftPrepare.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetCommit': grpc.unary_unary_rpc_method_handler(
          servicer.GetCommit,
          request_deserializer=pbft__pb2.PbftCommit.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PbftService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
