# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='protobufs',
  syntax='proto3',
  serialized_options=_b('Z\014./;protobufs'),
  serialized_pb=_b('\n\rmonitor.proto\x12\tprotobufs\"\x97\x01\n\x0eMetricsRequest\x12\x12\n\nthroughput\x18\x01 \x03(\x05\x12\x0f\n\x07latency\x18\x02 \x03(\x05\x12\x10\n\x08requests\x18\x03 \x03(\x05\x12\x15\n\rrequests_size\x18\x04 \x03(\x05\x12\x11\n\tBatchSize\x18\x05 \x03(\x05\x12\x14\n\x0c\x42\x61tchTimeout\x18\x06 \x03(\x05\x12\x0e\n\x06Leader\x18\x07 \x03(\x05\":\n\x0fMetricsResponse\x12\x11\n\tBatchSize\x18\x01 \x01(\x05\x12\x14\n\x0c\x42\x61tchTimeout\x18\x02 \x01(\x05\"\x1e\n\tTimestamp\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x32\x8d\x01\n\x0eMetricsService\x12\x44\n\x0bSendMetrics\x12\x19.protobufs.MetricsRequest\x1a\x1a.protobufs.MetricsResponse\x12\x35\n\x07\x43onnect\x12\x14.protobufs.Timestamp\x1a\x14.protobufs.TimestampB\x0eZ\x0c./;protobufsb\x06proto3')
)




_METRICSREQUEST = _descriptor.Descriptor(
  name='MetricsRequest',
  full_name='protobufs.MetricsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='throughput', full_name='protobufs.MetricsRequest.throughput', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latency', full_name='protobufs.MetricsRequest.latency', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requests', full_name='protobufs.MetricsRequest.requests', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requests_size', full_name='protobufs.MetricsRequest.requests_size', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BatchSize', full_name='protobufs.MetricsRequest.BatchSize', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BatchTimeout', full_name='protobufs.MetricsRequest.BatchTimeout', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Leader', full_name='protobufs.MetricsRequest.Leader', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=180,
)


_METRICSRESPONSE = _descriptor.Descriptor(
  name='MetricsResponse',
  full_name='protobufs.MetricsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BatchSize', full_name='protobufs.MetricsResponse.BatchSize', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BatchTimeout', full_name='protobufs.MetricsResponse.BatchTimeout', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=240,
)


_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='protobufs.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='protobufs.Timestamp.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=272,
)

DESCRIPTOR.message_types_by_name['MetricsRequest'] = _METRICSREQUEST
DESCRIPTOR.message_types_by_name['MetricsResponse'] = _METRICSRESPONSE
DESCRIPTOR.message_types_by_name['Timestamp'] = _TIMESTAMP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetricsRequest = _reflection.GeneratedProtocolMessageType('MetricsRequest', (_message.Message,), dict(
  DESCRIPTOR = _METRICSREQUEST,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.MetricsRequest)
  ))
_sym_db.RegisterMessage(MetricsRequest)

MetricsResponse = _reflection.GeneratedProtocolMessageType('MetricsResponse', (_message.Message,), dict(
  DESCRIPTOR = _METRICSRESPONSE,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.MetricsResponse)
  ))
_sym_db.RegisterMessage(MetricsResponse)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMP,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.Timestamp)
  ))
_sym_db.RegisterMessage(Timestamp)


DESCRIPTOR._options = None

_METRICSSERVICE = _descriptor.ServiceDescriptor(
  name='MetricsService',
  full_name='protobufs.MetricsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=275,
  serialized_end=416,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMetrics',
    full_name='protobufs.MetricsService.SendMetrics',
    index=0,
    containing_service=None,
    input_type=_METRICSREQUEST,
    output_type=_METRICSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='protobufs.MetricsService.Connect',
    index=1,
    containing_service=None,
    input_type=_TIMESTAMP,
    output_type=_TIMESTAMP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METRICSSERVICE)

DESCRIPTOR.services_by_name['MetricsService'] = _METRICSSERVICE

# @@protoc_insertion_point(module_scope)
